<?php

declare(strict_types=1);

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function getDisabledComments(): array
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT c, est
                FROM App\Entity\Comment c
                LEFT JOIN c.estate est
                WHERE c.enabled = false
                ORDER BY c.createdAt DESC
            ')
            ->getResult();
    }

    public function countDisabledComments(): int
    {
        return (int) $this->getEntityManager()
            ->createQuery('SELECT COUNT(c.id) FROM App\Entity\Comment c WHERE c.enabled = false')
            ->getSingleScalarResult();
    }

    public function getEnabledComments(): array
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT c, est
                FROM App\Entity\Comment c
                LEFT JOIN c.estate est
                WHERE c.enabled = true
                ORDER BY c.createdAt DESC
            ')
            ->getResult();
    }

    public function findAllComments(): array
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT c, est
                FROM App\Entity\Comment c
                LEFT JOIN c.estate est
                ORDER BY c.createdAt DESC
            ')
            ->getResult();
    }

}
