<?php

declare(strict_types=1);

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function getDisabledComments(): array
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT c
                FROM App\Entity\Comment c
                WHERE (c.enabled = false)
                ORDER BY c.createdAt DESC
            ');
        return $query->getResult();
    }

    public function countDisabledComments(): int
    {
        return (int) $this->getEntityManager()
            ->createQuery('SELECT COUNT(c.id) FROM App\Entity\Comment c WHERE c.enabled = false')
            ->getSingleScalarResult();
    }

    public function getEnabledComments()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT c
                FROM App\Entity\Comment c
                WHERE (c.enabled = true)
                ORDER BY c.createdAt DESC
            ');
        return $query->getResult();
    }

    public function findAllComments()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT c
                FROM App\Entity\Comment c
                ORDER BY c.createdAt DESC
            ');
        return $query->getResult();
    }

}
