hwi_oauth:
    connect:
        account_connector: my.custom.user_provider
    firewall_names: [main]
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_client_id%"
            client_secret:       "%facebook_client_secret%"
            options:
                display:    popup
            csrf:                true
            scope:               "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)"
            paths:
                email:          email
                profilepicture: picture.data.url

        google:
            type:         google
            client_id:    "%google_client_id%"
            client_secret: "%google_client_secret%"
            scope:        "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email: email

        vkontakte:
            type:          vkontakte
            client_id:     "%vkontakte_client_id%"
            client_secret: "%vkontakte_client_secret%"
            scope:         email status