hwi_oauth:
    connect:
        account_connector: my.custom.user_provider
    firewall_names: [main]
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%env(FACEBOOK_CLIENT_ID)%"
            client_secret:       "%env(FACEBOOK_CLIENT_SECRET)%"
            options:
                display:    popup
            csrf:                true
            scope:               "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)"
            paths:
                email:          email
                profilepicture: picture.data.url

        google:
            type:         google
            client_id:    "%env(GOOGLE_CLIENT_ID)%"
            client_secret: "%env(GOOGLE_CLIENT_SECRET)%"
            scope:        "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email: email

        vkontakte:
            type:          vkontakte
            client_id:     "%env(VKONTAKTE_CLIENT_ID)%"
            client_secret: "%env(VKONTAKTE_CLIENT_SECRET)%"
            scope:         email status
