<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;


/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getCategoriesWithChildren()
    {
        return $this->createQueryBuilder('category')
            ->select('category, children')
            ->leftJoin('category.children', 'children')
            ->getQuery()
            ->getResult();
    }

}
