<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function getDisabledComments()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT c
                FROM AppBundle:Comment c
                WHERE (c.enabled = false)
            ');
        return $query->getResult();
    }

}
