<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstateRepository extends EntityRepository
{
    public function getEstateExclusiveWithFiles()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT e, f
                FROM AppBundle:Estate e
                LEFT JOIN e.files f
                WHERE (e.exclusive = true)
            ');
        return $query->getResult();

    }
    public function getEstateFromCategory($slug)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT e, c, f
                FROM AppBundle:Estate e
                LEFT JOIN e.category c
                LEFT JOIN e.files f
                WHERE (c.title = :slug)
            ');
        $query->setParameter('slug', $slug);
        return $query->getResult();
    }

    public function getEstateWithDistrictComment($slug)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT e, d, com, f
                FROM AppBundle:Estate e
                LEFT JOIN e.district d
                LEFT JOIN e.comments com
                LEFT JOIN e.files f
                WHERE (e.slug = :slug)
            ');
        $query->setParameter('slug', $slug);
        return $query->getResult();

    }

    public function getEstatesWithAll() {
        return $this->createQueryBuilder('estate')
            ->select('estate, district, file, category')
            ->orderBy('estate.createdAt', 'DESC')
            ->leftJoin('estate.district', 'district')
            ->leftJoin('estate.category', 'category')
            ->leftJoin('estate.files', 'file')
            ->getQuery()
            ->getResult();
    }

    public function getOneEstateWithAll($slug) {
        return $this->createQueryBuilder('estate')
            ->select('estate, district, file, category, comment')
            ->where('estate.slug = :slug')
            ->leftJoin('estate.district', 'district')
            ->leftJoin('estate.category', 'category')
            ->leftJoin('estate.comments', 'comment')
            ->leftJoin('estate.files', 'file')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getEstatesOfManager($manager) {
        return $this->createQueryBuilder('estate')
            ->select('estate, file')
            ->where('estate.createdBy = :manager')
            ->leftJoin('estate.files', 'file')
            ->setParameter('manager', $manager)
            ->getQuery()
            ->getResult();
    }
}
