<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstateRepository extends EntityRepository
{
    public function getEstateFromCategory($slug)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT e, c
                FROM AppBundle:Estate e
                LEFT JOIN e.category c
                WHERE (c.title = :slug)
            ');
        $query->setParameter('slug', $slug);
        return $query->getResult();
    }

}
