hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login-social

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

vkontakte_login:
    path: /login/check-vkontakte

logout:
    path: /logout

app_admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     attribute

app:
    resource: "@AppBundle/Controller/"
    type:     attribute
    prefix:   /{_locale}
    requirements:
        _locale: "%app_locales%"
    defaults:
        _locale: "%locale%"
    exclude:
        - "@AppBundle/Controller/Admin/"

homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle\Controller\SiteController::indexAction, _locale: uk }
    requirements:
        _locale: uk|en

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"