services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/App'
        exclude:
            - '../src/App/Entity'
            - '../src/App/Form'
            - '../src/App/Repository'
            - '../src/App/DataFixtures'

    App\DataFixtures\ORM\Dev\:
        resource: '../src/App/DataFixtures/ORM/Dev'
        tags: ['doctrine.fixture.orm']

    App\DataFixtures\ORM\Deploy\:
        resource: '../src/App/DataFixtures/ORM/Deploy'
        tags: ['doctrine.fixture.orm']

    App\Controller\:
        resource: '../src/App/Controller'
        public: true

    my.custom.user_provider:
        alias: App\Security\Core\User\OAuthUserProvider
        public: true

    App\EventListener\RedirectToPreferredLocaleListener:
        bind:
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'

    App\Twig\AppExtension:
        bind:
            $locales: '%app_locales%'

    App\Utils\BreadcrumpsMaker:
        arguments:
            - '@white_october_breadcrumbs'

    App\Controller\SiteController:
        public: true
        bind:
            $breadcrumbs: '@white_october_breadcrumbs'
            $pdf: '@knp_snappy.pdf'
